### ISSUE TITLE
Can't find vulkan layer?

### ISSUE THREAD

**Issue by flukejones** [kvark/blade#75]
I'd never heard of blade until zed merged it in. Unsure what environment you use, but for me nothing works:

Operating System: Fedora Linux 40
KDE Plasma Version: 5.93.0
KDE Frameworks Version: 5.249.0
Qt Version: 6.6.1
Kernel Version: 6.7.4-666.rog.fc40.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 32 × 13th Gen Intel® Core™ i9-13980HX
Memory: 31.0 GiB of RAM
Graphics Processor: Mesa Intel® Graphics
Manufacturer: ASUSTeK COMPUTER INC.
Product Name: ROG Strix G634JZ_G634JZ_00016247D
System Version: 1.0

Fails also with attempt to offload to Nvidia dgpu.

```
❯ RUST_BACKTRACE=full cargo run --example bunnymark
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/examples/bunnymark`
thread 'main' panicked at blade-graphics/src/vulkan/init.rs:281:55:
called `Result::unwrap()` on an `Err` value: ERROR_LAYER_NOT_PRESENT
stack backtrace:
   0:     0x562d657cc56c - std::backtrace_rs::backtrace::libunwind::trace::ha637c64ce894333a
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x562d657cc56c - std::backtrace_rs::backtrace::trace_unsynchronized::h47f62dea28e0c88d
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x562d657cc56c - std::sys_common::backtrace::_print_fmt::h9eef0abe20ede486
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x562d657cc56c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hed7f999df88cc644
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x562d657f8f30 - core::fmt::rt::Argument::fmt::h1539a9308b8d058d
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/rt.rs:142:9
   5:     0x562d657f8f30 - core::fmt::write::h3a39390d8560d9c9
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/mod.rs:1120:17
   6:     0x562d657c97ff - std::io::Write::write_fmt::h5fc9997dfe05f882
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/io/mod.rs:1762:15
   7:     0x562d657cc354 - std::sys_common::backtrace::_print::h894006fb5c6f3d45
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x562d657cc354 - std::sys_common::backtrace::print::h23a2d212c6fff936
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x562d657cd867 - std::panicking::default_hook::{{closure}}::h8a1d2ee00185001a
  10:     0x562d657cd5cf - std::panicking::default_hook::h6038f2eba384e475
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:292:9
  11:     0x562d657cdd58 - std::panicking::rust_panic_with_hook::h2b5517d590cab22e
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:779:13
  12:     0x562d657cdc3e - std::panicking::begin_panic_handler::{{closure}}::h233112c06e0ef43e
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:657:13
  13:     0x562d657cca36 - std::sys_common::backtrace::__rust_end_short_backtrace::h6e893f24d7ebbff8
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x562d657cd9a2 - rust_begin_unwind
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
  15:     0x562d657f6905 - core::panicking::panic_fmt::hbf0e066aabfa482c
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
  16:     0x562d657f6ed3 - core::result::unwrap_failed::hddb4fea594200c52
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1653:5
  17:     0x562d6551d61e - core::result::Result<T,E>::unwrap::h7a2493d53caee515
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1077:23
  18:     0x562d65532694 - blade_graphics::hal::init::<impl blade_graphics::hal::Context>::init_impl::hf4f189f691033b16
                               at /home/luke/Projects/blade/blade-graphics/src/vulkan/init.rs:281:13
  19:     0x562d64d48443 - blade_graphics::hal::init::<impl blade_graphics::hal::Context>::init_windowed::h1696d837165f130f
                               at /home/luke/Projects/blade/blade-graphics/src/vulkan/init.rs:562:9
  20:     0x562d64d80e31 - bunnymark::Example::new::h7959c649ee3bf0e5
                               at /home/luke/Projects/blade/examples/bunnymark/main.rs:57:13
  21:     0x562d64d82b14 - bunnymark::main::hc32685f80d6861d9
                               at /home/luke/Projects/blade/examples/bunnymark/main.rs:306:23
  22:     0x562d64da525b - core::ops::function::FnOnce::call_once::heb158917feda7b80
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5
  23:     0x562d64d4360e - std::sys_common::backtrace::__rust_begin_short_backtrace::hfba5955c6345884a
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:154:18
  24:     0x562d64d580b1 - std::rt::lang_start::{{closure}}::h3527050a22ae0255
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:167:18
  25:     0x562d657c41b7 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hd95060ecd5e1ca24
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:284:13
  26:     0x562d657c41b7 - std::panicking::try::do_call::h6e8cf51db32a6e4b
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  27:     0x562d657c41b7 - std::panicking::try::h3a52eefe24fe3c29
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  28:     0x562d657c41b7 - std::panic::catch_unwind::h24c28c23c02c3841
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  29:     0x562d657c41b7 - std::rt::lang_start_internal::{{closure}}::h705d3c9cbc06ef47
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:48
  30:     0x562d657c41b7 - std::panicking::try::do_call::ha21f52ba13158470
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  31:     0x562d657c41b7 - std::panicking::try::h5581346bf6aeb1f8
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  32:     0x562d657c41b7 - std::panic::catch_unwind::h7919645a6b72e25b
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  33:     0x562d657c41b7 - std::rt::lang_start_internal::h12de51168669836e
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:20
  34:     0x562d64d5808a - std::rt::lang_start::h17af736eef4d3cce
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:166:17
  35:     0x562d64d82f5e - main
  36:     0x7fb189c87088 - __libc_start_call_main
  37:     0x7fb189c8714b - __libc_start_main_impl
  38:     0x562d64d43535 - _start
  39:                0x0 - <unknown>
warning: queue 0x562d6696b5e0 destroyed while proxies still attached:
  xdg_wm_base@24 still attached
  wl_output@15 still attached
  zwp_text_input_manager_v3@14 still attached
  xdg_activation_v1@13 still attached
  wl_subcompositor@12 still attached
  zwp_relative_pointer_manager_v1@11 still attached
  zwp_pointer_constraints_v1@10 still attached
  wl_seat@9 still attached
  wl_shm@8 still attached
  wp_fractional_scale_manager_v1@7 still attached
  wp_viewporter@6 still attached
  zxdg_decoration_manager_v1@5 still attached
  wl_compositor@4 still attached
  wl_registry@2 still attached
```

wgpu works fine.

**Comment by kvark** [comment]
Vulkan validation layer is currently explicitly requested by Zed (it's not hardcoded into Blade) when building in debug. Once Linux Zed ships, we'll disable it entirely. For development on Linux, I recommend installing the [validation layers](https://packages.ubuntu.com/search?keywords=vulkan-validationlayers) since it helps during development.

**Comment by flukejones** [comment]
I see. And this is also compulsory for the examples?

**Comment by kvark** [comment]
It's this flag - https://github.com/kvark/blade/blob/0dd584ae02f052aa19b8745d63793c67474ffc68/examples/bunnymark/main.rs#L60
If you don't want to install the validation layers, just turn off this validation flag in code.

Part of the reason I want it enabled in debug mode (for the repo examples) is - Blade is designed as unsafe API, so I want to immediately see if something goes wrong. You don't need it in `wgpu` because it's designed to be safe.

**Comment by kanerogers** [comment]
Just my 2 cents but Vulkan Configurator is the best way to go when wanting to enable/disable Vulkan validation layers, as it can avoid situations like these where the layers are inadvertantly enabled/disabled. 😄

**Comment by flukejones** [comment]
@kvark forgot to come back and say thanks for the pointer. Blade looks pretty interesting too, I think I need to have a tinker with it using my Doom engine.

Also yes, maybe a different way to enforce validation layers would be better? At the least it would prevent newbies like myself from tripping up.

**Comment by kvark** [comment]
Yes, agreed, let's disable it in Zed by default - https://github.com/zed-industries/zed/pull/8044
